$data = @(
    [PSCustomObject]@{序号=1; 公司名称="Nashville Wraps"; 网址="nashvillewraps.com"; "重点联系人 (采购/开发)"="Angela Bauer"; 职位="Product Dev Mgr / Senior Buyer"; 邮箱="abauer@nashvillewraps.com"; "手机/直拨"="1-800-547-9727 (转采购)"; 所在地="TN, USA"; 切入角度="该司主打环保礼品包装，可推荐其核心款式的工厂直供方案。"; "海关数据/体量 (估)"="$1000万+"},
    [PSCustomObject]@{序号=2; 公司名称="Paper Mart"; 网址="papermart.com"; "重点联系人 (采购/开发)"="Howard Chubbuck Jr."; 职位="Purchasing Manager"; 邮箱="hchubbuck@papermart.com"; "手机/直拨"="714-787-4900"; 所在地="CA, USA"; 切入角度="超大型批发商，痛点在于高周转和成本控制。"; "海关数据/体量 (估)"="$5000万+"},
    [PSCustomObject]@{序号=3; 公司名称="Tiny Box Company"; 网址="tinyboxcompany.co.uk"; "重点联系人 (采购/开发)"="Harry Chivers"; 职位="Assistant Box Buyer"; 邮箱="harry@tinyboxcompany.co.uk"; "手机/直拨"="+44 01825 723 832"; 所在地="UK"; 切入角度="主打环保奢华感，强调再生纸材质和 FSC 认证。"; "海关数据/体量 (估)"="$200万-500万"},
    [PSCustomObject]@{序号=4; 公司名称="Westpack"; 网址="westpack.com"; "重点联系人 (采购/开发)"="Martin Haugaard Andersen"; 职位="Sourcing Manager"; 邮箱="mha@westpack.com"; "手机/直拨"="+45 70 200 230"; 所在地="Denmark"; 切入角度="丹麦高端珠宝/礼品盒商。切入其高端礼盒定制线。"; "海关数据/体量 (估)"="$1000万-2000万"},
    [PSCustomObject]@{序号=5; 公司名称="Mid-Atlantic Packaging"; 网址="midatlanticpackaging.com"; "重点联系人 (采购/开发)"="Heather Uselton"; 职位="Purchasing Manager"; 邮箱="huselton@midatlanticpackaging.com"; "手机/直拨"="1-800-284-1332"; 所在地="DE, USA"; 切入角度="专注定制印刷。可提供各类纸袋、礼盒的印刷方案。"; "海关数据/体量 (估)"="$500万-800万"},
    [PSCustomObject]@{序号=6; 公司名称="BRP Box Shop"; 网址="brpboxshop.com"; "重点联系人 (采购/开发)"="Steve Swamberger"; 职位="President / Owner"; 邮箱="sswamberger@bigriverpackaging.com"; "手机/直拨"="(563) 243-5210"; 所在地="IA, USA"; 切入角度="烘焙盒专家。提供食品级 FDA 认证及低成本报价。"; "海关数据/体量 (估)"="$300万-500万"},
    [PSCustomObject]@{序号=7; 公司名称="Southern Champion Tray"; 网址="sctray.com"; "重点联系人 (采购/开发)"="Misty Brooks-Vidal"; 职位="Purchasing Manager"; 邮箱="mbrooks-vidal@sctray.com"; "手机/直拨"="(423) 756-5121"; 所在地="TN, USA"; 切入角度="老牌纸板包装商。补充其烘焙/零售包装产能。"; "海关数据/体量 (估)"="$2000万+"},
    [PSCustomObject]@{序号=8; 公司名称="Selfor Paris"; 网址="selforparis.com"; "重点联系人 (采购/开发)"="Franck Meyer"; 职位="Managing Director"; 邮箱="franck.meyer@selforparis.com"; "手机/直拨"="+33 1 42 78 06 66"; 所在地="France"; 切入角度="巴黎珠宝包装专家。推荐比欧产更具优势的中国造方案。"; "海关数据/体量 (估)"="$300万-500万"},
    [PSCustomObject]@{序号=9; 公司名称="Gunther Mele"; 网址="gunthermele.com"; "重点联系人 (采购/开发)"="Mainul Bashar"; 职位="Dir. of Purchasing & SCM"; 邮箱="mbashar@gunthermele.com"; "手机/直拨"="(888) 486-8437"; 所在地="Canada"; 切入角度="160年零售包装商。切入高端礼品袋和纸盒线。"; "海关数据/体量 (估)"="$1500万+"},
    [PSCustomObject]@{序号=10; 公司名称="PakFactory"; 网址="pakfactory.com"; "重点联系人 (采购/开发)"="Diana Lai"; 职位="Operations Manager"; 邮箱="diana@pakfactory.com"; "手机/直拨"="1-888-622-2819"; 所在地="Canada/USA"; 切入角度="现代定制平台。强调快速反应能力和精美打样。"; "海关数据/体量 (估)"="$500万-1000万"},
    [PSCustomObject]@{序号=11; 公司名称="EcoEnclose"; 网址="ecoenclose.com"; "重点联系人 (采购/开发)"="Jessica Stewart"; 职位="Purchasing Manager"; 邮箱="jessica.stewart@ecoenclose.com"; "手机/直拨"="1-888-445-6575"; 所在地="CO, USA"; 切入角度="可持续包装领军者。推荐 100% 再生纸礼品袋。"; "海关数据/体量 (估)"="$1000万-2000万"},
    [PSCustomObject]@{序号=12; 公司名称="Packlane"; 网址="packlane.com"; "重点联系人 (采购/开发)"="Josh Asselin"; 职位="Sourcing Manager"; 邮箱="josh.asselin@packlane.com"; "手机/直拨"="1-844-428-2780"; 所在地="CA, USA"; 切入角度="专注于定制纸盒。推荐高强度、印刷精美的邮寄盒。"; "海关数据/体量 (估)"="$1000万+"},
    [PSCustomObject]@{序号=13; 公司名称="Macfarlane Packaging"; 网址="macfarlanepackaging.com"; "重点联系人 (采购/开发)"="Alan Heald"; 职位="Procurement Manager"; 邮箱="alan.heald@macfarlanepackaging.com"; "手机/直拨"="+44 0800 2 88 88 22"; 所在地="UK"; 切入角度="英国最大包装商。主推低成本纸袋和礼品盒。"; "海关数据/体量 (估)"="$5000万+"},
    [PSCustomObject]@{序号=14; 公司名称="GWP Group"; 网址="gwp.co.uk"; "重点联系人 (采购/开发)"="Adele Heather"; 职位="Purchasing Manager"; 邮箱="adele.heather@gwp.co.uk"; "手机/直拨"="+44 01793 754 444"; 所在地="UK"; 切入角度="保护性包装专家。推荐防震缓冲礼盒结构设计。"; "海关数据/体量 (估)"="$500万-800万"},
    [PSCustomObject]@{序号=15; 公司名称="BIDBI"; 网址="bidbi.co.uk"; "重点联系人 (采购/开发)"="Daya"; 职位="Managing Director"; 邮箱="daya@bidbi.co.uk"; "手机/直拨"="+44 0114 272 1201"; 所在地="UK"; 切入角度="专注各类包装袋。主推精美纸质礼品袋。"; "海关数据/体量 (估)"="$100万-300万"},
    [PSCustomObject]@{序号=16; 公司名称="BOXFOX"; 网址="boxfox.com"; "重点联系人 (采购/开发)"="Ericka Schmiester"; 职位="Director of Operations"; 邮箱="ericka@shopboxfox.com"; "手机/直拨"="(310) 862-2460"; 所在地="CA, USA"; 切入角度="精品礼盒策展商。切入其定制刚性礼盒。"; "海关数据/体量 (估)"="$300万-500万"},
    [PSCustomObject]@{序号=17; 公司名称="Fantastapack"; 网址="fantastapack.com"; "重点联系人 (采购/开发)"="Mark Stacey"; 职位="Dir. of Americas Procurement"; 邮箱="mark.stacey@boxmaker.com"; "手机/直拨"="(800) 443-5431"; 所在地="WA, USA"; 切入角度="定制瓦楞盒专家。推荐高档彩色印刷礼盒。"; "海关数据/体量 (估)"="$1000万+"},
    [PSCustomObject]@{序号=18; 公司名称="Fold-Pak"; 网址="fold-pak.com"; "重点联系人 (采购/开发)"="Sondra Hale"; 职位="Purchasing Manager"; 邮箱="sondra.hale@westrock.com"; "手机/直拨"="(615) 444-6250"; 所在地="TN, USA"; 切入角度="专注餐饮盒。提供具价格竞争力的直采价。"; "海关数据/体量 (估)"="$1000万+"},
    [PSCustomObject]@{序号=19; 公司名称="BioPak"; 网址="biopak.com"; "重点联系人 (采购/开发)"="Larry Chang"; 职位="Procurement Specialist"; 邮箱="larry@hdbiopak.com"; "手机/直拨"="(281) 888-0000"; 所在地="Global/USA"; 切入角度="全球可持续包装商。主推 FSC 认证蛋糕盒。"; "海关数据/体量 (估)"="$3000万+"},
    [PSCustomObject]@{序号=20; 公司名称="The Bag Broker"; 网址="thebagbroker.eu"; "重点联系人 (采购/开发)"="Mihai Toth"; 职位="EU General Manager"; 邮箱="mihai@thebagbroker.com"; "手机/直拨"="+31 (40) 7988050"; 所在地="Netherlands"; 切入角度="欧洲袋类专家。切入礼品袋和精品纸袋线。"; "海关数据/体量 (估)"="$500万-800万"}
)

$data | Export-Csv -Path "iColorPack_欧美客户清单_正式版.csv" -NoTypeInformation -Encoding UTF8
